---
apiVersion: v1
name: aws-cloud-controller-manager
description: This will install Cloud Controller Manager for AWS Cloud Provider
version: 0.0.1
appVersion: v1.19.0-alpha.1
maintainers:
- name: Jeswin K Ninan
  email: jeswinjkn@gmail.com
---