---
apiVersion: v1
name: aws-cloud-controller-manager
description: Installs Cloud Controller Manager for AWS Cloud Provider
version: 0.0.2
appVersion: v1.20.0-alpha.0
maintainers:
- name: Jeswin K Ninan
  email: jeswinjkn@gmail.com
- name: Ayberk Yilmaz
  email: yayberk@amazon.com
---
